version: 2.1

orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn package
      - persist_to_workspace:
          root: .
          paths:
            - target/*.jar
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - eb/deploy:
          context: aws-creds
          application-name: admin
          environment-name: Admin-env
          label: version-<<pipeline.number>>
          requires:
            - build