version: 2.1

orbs:
  aws-elasticbeanstalk: circleci/aws-elasticbeanstalk@2.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn package
      - persist_to_workspace:
          root: .
          paths:
            - target/*.jar

  deploy:
    executor: aws-elasticbeanstalk/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-elasticbeanstalk/deploy:
          app_name: admin
          env_name: Admin-env
          version_label: v${CIRCLE_BUILD_NUM}
          source_bundle: /tmp/workspace/target/admin-0.0.1-SNAPSHOT.jar
          region: us-east-1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
