version: '2'
services:
  admin-app:
    image: admin
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://admin-mysql:3306/admin?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  shop-mysql:
    extends:
      file: mysql.yml
      service: admin-mysql
  admin-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: admin-elasticsearch
